module.exports = {
  "react-hooks/exhaustive-deps": "warn",
  "react-hooks/rules-of-hooks": "warn",
  "react/prop-types": "off",
  "react/no-unescaped-entities": "off",
  "react/jsx-first-prop-new-line": ["error", "multiline"],
  "react/jsx-fragments": "warn",
  "@typescript-eslint/type-annotation-spacing": "warn",
  "react/jsx-max-props-per-line": ["error", { maximum: 1, when: "multiline" }],
  "react/jsx-tag-spacing": ["warn", { beforeClosing: "never" }],
  "react/jsx-closing-bracket-location": ["warn", "tag-aligned"],
  "react/jsx-wrap-multilines": ["warn", {
    declaration: "parens-new-line",
    assignment: "parens-new-line",
    return: "parens-new-line",
    arrow: "parens-new-line",
    condition: "parens-new-line",
    logical: "parens-new-line",
    prop: "parens-new-line"
  }],
  "react/jsx-boolean-value": ["warn", "never"],
  "react/jsx-closing-tag-location": "warn",
  "react/jsx-curly-brace-presence": ["warn", { props: "never", children: "never" }],
  "react/jsx-curly-newline": ["warn", { multiline: "forbid", singleline: "forbid" }],
  "react/jsx-curly-spacing": ["warn", "never"],
  "react/jsx-equals-spacing": "warn",
  "react/jsx-indent-props": ["warn", 2],
  "react/jsx-indent": ["warn", 2],
  "react/jsx-props-no-multi-spaces": "warn",
  "react/no-danger-with-children": "error",
  "react/no-deprecated": "error",
  "react/no-direct-mutation-state": "error",
  "react/display-name": "off",
  "react/jsx-child-element-spacing": "error"
};
